name: pinopoint_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/pinopointfront.png
  - assets/startgame.png
  - assets/categorybg.png
  - assets/pinpointluzon.png
  - assets/pinpointvisayas.png
  - assets/pinpointmindanao.png
  - assets/luzonotwbg.png
  - assets/visayasotwbg.png
  - assets/mindanaootwbg.png
  - assets/rizalpark.png
  - assets/skyranchtagaytay.png
  - assets/moa.png
  - assets/fortsantiago.png
  - assets/mayonvolcano.png
  - assets/boracay.png
  - assets/chocolatehills.png
  - assets/kawasanfalls.png
  - assets/magellanscross.png
  - assets/sambawanisland.png